### ISSUE TITLE
PHP开启php-pecl-trace扩展会造成redis线程池创建后没有返回的问题。

### ISSUE THREAD

**Issue by xiangjihan** [swoft-cloud/swoft-redis#1]
已经测试和影响到的版本：
PHP 7.1 7.2
Swoole 2.1.1
swoft 1.0.0

复现：
开启php-pecl-trace扩展，在Controller代码中操作redis,请求一直加载，没有任何返回。同时，其余请求不受影响。也没有异常、错误的打印或者日志输出。

建议：
暂时关闭或者卸载php-pecl-trace扩展，如果遇到其他一些奇怪问题，请先考虑PHP的相关调试扩展与swoole不兼容的可能性。

原因：
不明

**Comment by huangzhhui** [comment]
请使用 Swoole 2.1.2-alpha 试一下，编译Swoole的master分支下的

**Comment by huangzhhui** [comment]
如 Swoole 2.1.2-alpha 无法解决再重开一下 issue

**Comment by inhere** [comment]
这个扩展应该跟 xdebug 之类的一样 会影响swoole
